package com.vitral.enumerations;

public enum BookGenre {
    ROMANCE, FICCAO, FANTASIA, TERROR, SUSPENSE, MISTERIO, AVENTURA, BIOGRAFIA,
    HISTORIA, FILOSOFIA, POESIA, AUTOAJUDA, INFANTIL, TECNICO, DIDATICO, OUTROS
}
